### ISSUE TITLE
yout app is broke in heroku check it

### ISSUE THREAD

**Issue by pyropecs** [jigar-sable/flipkart-mern#1]
your web app which is hosted in heroku had been broken kindly check it.i think heroku going to stop its free services so it deletes the inactive accounts present there.so may be that is the problem

**Comment by Sagar-Gondage** [comment]
I am able to see only below error image

![image](https://user-images.githubusercontent.com/99082133/191352512-7dd09f77-2839-422f-a248-78133501b89e.png)

**Comment by jigar-sable** [comment]
Yes heroku service is closed.
